// Code generated by go generate
// This file was generated by robots at 2018-03-27 01:14:06.341346379 +0000 UTC

package optional

import (
	"encoding/json"
	"errors"
)

// Int32 is an optional int32
type Int32 struct {
	value *int32
}

// NewInt32 creates a optional.Int32 from a int32
func NewInt32(v int32) Int32 {
	return Int32{&v}
}

// Set sets the int32 value
func (i Int32) Set(v int32) {
	i.value = &v
}

// Get returns the int32 value or an error if not present
func (i Int32) Get() (int32, error) {
	if !i.Present() {
		return *i.value, errors.New("value not present")
	}
	return *i.value, nil
}

// Present returns whether or not the value is present
func (i Int32) Present() bool {
	return i.value != nil
}

// OrElse returns the int32 value or a default value if the value is not present
func (i Int32) OrElse(v int32) int32 {
	if i.Present() {
		return *i.value
	}
	return v
}

// If calls the function f with the value if the value is present
func (i Int32) If(fn func(int32)) {
	if i.Present() {
		fn(*i.value)
	}
}

func (i Int32) MarshalJSON() ([]byte, error) {
	if i.Present() {
		return json.Marshal(i.value)
	}
	var zero int32
	return json.Marshal(zero)
}

func (i *Int32) UnmarshalJSON(data []byte) error {
	var value int32

	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	i.value = &value
	return nil
}
