servers:
  - default_log_path: stdout
    routers:
      - router_config_name: server_router
        virtual_hosts:
          - name: serverHost
            domains:
              - '*'
            routers:
              - match:
                  prefix: /
                route:
                  cluster_name: serverCluster
    listeners:
      - name: serverListener
        address: '127.0.0.1:2046'
        bind_port: true
        filter_chains:
          - filters:
              - type: proxy
                config:
                  downstream_protocol: Http1
                  upstream_protocol: Http1
                  router_config_name: server_router
cluster_manager:
  clusters:
    - name: serverCluster
      type: SIMPLE
      lb_type: LB_RANDOM
      max_request_per_conn: 1024
      conn_buffer_limit_bytes: 32768
      hosts:
        - address: '127.0.0.1:8080'
tracing:
  enable: true
  driver: Zipkin
  config:
    service_name: MOSN
    reporter: http
    addresses:
      - "http://localhost:9411/api/v2/spans"
    http:
      timeout: 3
      batch_size: 1
      batch_interval: 1

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 34901
