// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mixer/v1/config/client/api_spec.proto

package client

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "istio.io/gogo-genproto/googleapis/google/api"
	math "math"
	_ "mosn.io/mosn/istio/istio1106/mixer/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DeepCopyInto supports using HTTPAPISpec within kubernetes types, where deepcopy-gen is used.
func (in *HTTPAPISpec) DeepCopyInto(out *HTTPAPISpec) {
	p := proto.Clone(in).(*HTTPAPISpec)
	*out = *p
}

// DeepCopyInto supports using HTTPAPISpecBinding within kubernetes types, where deepcopy-gen is used.
func (in *HTTPAPISpecBinding) DeepCopyInto(out *HTTPAPISpecBinding) {
	p := proto.Clone(in).(*HTTPAPISpecBinding)
	*out = *p
}
