// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: ip_access.proto

package pb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IpAccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DefaultAction string `protobuf:"bytes,1,opt,name=default_action,json=defaultAction,proto3" json:"default_action,omitempty"`
	Header        string `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Ips           []*IPS `protobuf:"bytes,3,rep,name=ips,proto3" json:"ips,omitempty"`
}

func (x *IpAccess) Reset() {
	*x = IpAccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ip_access_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IpAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpAccess) ProtoMessage() {}

func (x *IpAccess) ProtoReflect() protoreflect.Message {
	mi := &file_ip_access_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpAccess.ProtoReflect.Descriptor instead.
func (*IpAccess) Descriptor() ([]byte, []int) {
	return file_ip_access_proto_rawDescGZIP(), []int{0}
}

func (x *IpAccess) GetDefaultAction() string {
	if x != nil {
		return x.DefaultAction
	}
	return ""
}

func (x *IpAccess) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *IpAccess) GetIps() []*IPS {
	if x != nil {
		return x.Ips
	}
	return nil
}

type IPS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action string   `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Addrs  []string `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
}

func (x *IPS) Reset() {
	*x = IPS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ip_access_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPS) ProtoMessage() {}

func (x *IPS) ProtoReflect() protoreflect.Message {
	mi := &file_ip_access_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPS.ProtoReflect.Descriptor instead.
func (*IPS) Descriptor() ([]byte, []int) {
	return file_ip_access_proto_rawDescGZIP(), []int{1}
}

func (x *IPS) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *IPS) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

var File_ip_access_proto protoreflect.FileDescriptor

var file_ip_access_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x69, 0x70, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x64, 0x0a, 0x08, 0x49, 0x70, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x19, 0x0a, 0x03, 0x69, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e,
	0x70, 0x62, 0x2e, 0x49, 0x50, 0x53, 0x52, 0x03, 0x69, 0x70, 0x73, 0x22, 0x33, 0x0a, 0x03, 0x49,
	0x50, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64,
	0x64, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_ip_access_proto_rawDescOnce sync.Once
	file_ip_access_proto_rawDescData = file_ip_access_proto_rawDesc
)

func file_ip_access_proto_rawDescGZIP() []byte {
	file_ip_access_proto_rawDescOnce.Do(func() {
		file_ip_access_proto_rawDescData = protoimpl.X.CompressGZIP(file_ip_access_proto_rawDescData)
	})
	return file_ip_access_proto_rawDescData
}

var file_ip_access_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ip_access_proto_goTypes = []interface{}{
	(*IpAccess)(nil), // 0: pb.IpAccess
	(*IPS)(nil),      // 1: pb.IPS
}
var file_ip_access_proto_depIdxs = []int32{
	1, // 0: pb.IpAccess.ips:type_name -> pb.IPS
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ip_access_proto_init() }
func file_ip_access_proto_init() {
	if File_ip_access_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ip_access_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IpAccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ip_access_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ip_access_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ip_access_proto_goTypes,
		DependencyIndexes: file_ip_access_proto_depIdxs,
		MessageInfos:      file_ip_access_proto_msgTypes,
	}.Build()
	File_ip_access_proto = out.File
	file_ip_access_proto_rawDesc = nil
	file_ip_access_proto_goTypes = nil
	file_ip_access_proto_depIdxs = nil
}
