# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='plugin.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cplugin.proto\x12\x05proto\"\xde\x01\n\x07Request\x12*\n\x06header\x18\x01 \x03(\x0b\x32\x1a.proto.Request.HeaderEntry\x12,\n\x07trailer\x18\x02 \x03(\x0b\x32\x1b.proto.Request.TrailerEntry\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\x12\x0c\n\x04type\x18\x04 \x01(\t\x1a-\n\x0bHeaderEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0cTrailerEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xe3\x01\n\x08Response\x12+\n\x06header\x18\x01 \x03(\x0b\x32\x1b.proto.Response.HeaderEntry\x12-\n\x07trailer\x18\x02 \x03(\x0b\x32\x1c.proto.Response.TrailerEntry\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\x12\x0e\n\x06status\x18\x04 \x01(\x05\x1a-\n\x0bHeaderEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0cTrailerEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x31\n\x06Plugin\x12\'\n\x04\x43\x61ll\x12\x0e.proto.Request\x1a\x0f.proto.Responseb\x06proto3'
)




_REQUEST_HEADERENTRY = _descriptor.Descriptor(
  name='HeaderEntry',
  full_name='proto.Request.HeaderEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.Request.HeaderEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.Request.HeaderEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=198,
)

_REQUEST_TRAILERENTRY = _descriptor.Descriptor(
  name='TrailerEntry',
  full_name='proto.Request.TrailerEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.Request.TrailerEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.Request.TrailerEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=246,
)

_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='proto.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.Request.header', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trailer', full_name='proto.Request.trailer', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='proto.Request.body', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='proto.Request.type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_HEADERENTRY, _REQUEST_TRAILERENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=246,
)


_RESPONSE_HEADERENTRY = _descriptor.Descriptor(
  name='HeaderEntry',
  full_name='proto.Response.HeaderEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.Response.HeaderEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.Response.HeaderEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=198,
)

_RESPONSE_TRAILERENTRY = _descriptor.Descriptor(
  name='TrailerEntry',
  full_name='proto.Response.TrailerEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.Response.TrailerEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.Response.TrailerEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=246,
)

_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='proto.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.Response.header', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trailer', full_name='proto.Response.trailer', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='proto.Response.body', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='proto.Response.status', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RESPONSE_HEADERENTRY, _RESPONSE_TRAILERENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=476,
)

_REQUEST_HEADERENTRY.containing_type = _REQUEST
_REQUEST_TRAILERENTRY.containing_type = _REQUEST
_REQUEST.fields_by_name['header'].message_type = _REQUEST_HEADERENTRY
_REQUEST.fields_by_name['trailer'].message_type = _REQUEST_TRAILERENTRY
_RESPONSE_HEADERENTRY.containing_type = _RESPONSE
_RESPONSE_TRAILERENTRY.containing_type = _RESPONSE
_RESPONSE.fields_by_name['header'].message_type = _RESPONSE_HEADERENTRY
_RESPONSE.fields_by_name['trailer'].message_type = _RESPONSE_TRAILERENTRY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {

  'HeaderEntry' : _reflection.GeneratedProtocolMessageType('HeaderEntry', (_message.Message,), {
    'DESCRIPTOR' : _REQUEST_HEADERENTRY,
    '__module__' : 'plugin_pb2'
    # @@protoc_insertion_point(class_scope:proto.Request.HeaderEntry)
    })
  ,

  'TrailerEntry' : _reflection.GeneratedProtocolMessageType('TrailerEntry', (_message.Message,), {
    'DESCRIPTOR' : _REQUEST_TRAILERENTRY,
    '__module__' : 'plugin_pb2'
    # @@protoc_insertion_point(class_scope:proto.Request.TrailerEntry)
    })
  ,
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'plugin_pb2'
  # @@protoc_insertion_point(class_scope:proto.Request)
  })
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.HeaderEntry)
_sym_db.RegisterMessage(Request.TrailerEntry)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {

  'HeaderEntry' : _reflection.GeneratedProtocolMessageType('HeaderEntry', (_message.Message,), {
    'DESCRIPTOR' : _RESPONSE_HEADERENTRY,
    '__module__' : 'plugin_pb2'
    # @@protoc_insertion_point(class_scope:proto.Response.HeaderEntry)
    })
  ,

  'TrailerEntry' : _reflection.GeneratedProtocolMessageType('TrailerEntry', (_message.Message,), {
    'DESCRIPTOR' : _RESPONSE_TRAILERENTRY,
    '__module__' : 'plugin_pb2'
    # @@protoc_insertion_point(class_scope:proto.Response.TrailerEntry)
    })
  ,
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'plugin_pb2'
  # @@protoc_insertion_point(class_scope:proto.Response)
  })
_sym_db.RegisterMessage(Response)
_sym_db.RegisterMessage(Response.HeaderEntry)
_sym_db.RegisterMessage(Response.TrailerEntry)


_REQUEST_HEADERENTRY._options = None
_REQUEST_TRAILERENTRY._options = None
_RESPONSE_HEADERENTRY._options = None
_RESPONSE_TRAILERENTRY._options = None

_PLUGIN = _descriptor.ServiceDescriptor(
  name='Plugin',
  full_name='proto.Plugin',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=478,
  serialized_end=527,
  methods=[
  _descriptor.MethodDescriptor(
    name='Call',
    full_name='proto.Plugin.Call',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLUGIN)

DESCRIPTOR.services_by_name['Plugin'] = _PLUGIN

# @@protoc_insertion_point(module_scope)
